{% set name = "dockstring" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dockstring-{{ version }}.tar.gz
  sha256: 832730f294e88fbcf576347b494a5c3a96eee4e71b23819f6455b6fa053f9f9d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.7,<3.11
    - rdkit <2022.04
    - openbabel =3.1.1

test:
  imports:
    - dockstring
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dockstring/dockstring
  summary: Package for easy ligand preparation and docking with AutoDock Vina against a highly-curated selection of 58 protein targets. One of the three components of the DOCKSTRING bundle (package, dataset, and benchmark tasks).
  license: Apache-2.0
  license_file:
    - LICENSE
    - dockstring/resources/bin/LICENSE

extra:
  recipe-maintainers:
    - AustinT
